[tool.ruff]
line-length = 99

[tool.ruff.lint]
extend-select = [
    "I", # isort
]

[tool.black]
line-length = 99

[tool.mypy]
disallow_any_generics = true
disallow_untyped_defs = true
disallow_untyped_decorators = true
strict_equality = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_unreachable = true
enable_error_code = [
    "redundant-expr",
    "possibly-undefined",
    "truthy-bool",
    "ignore-without-code"
]
